'use strict';
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pageNames=['사건 도착','단서 추리','기사 수사','자료 수사','현장 확인','비교 탐구','사건 해결','탐정 보고서'];
const STORAGE='roadon-three-cases-v1';
const fresh=()=>({page:1,initial:'',initialQuestion:'',clue:0,notes:[],questions:[],opened:[],paired:[],completed:[],help:[],choices:[],evidence:[],answer:null,checks:[],field:'',compare:['',''],solution:['','',''],thought:'',done:false});
let active=0,records=CASES.map(fresh),timer=null,toastTimer=null,codeAction=null;
try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved?.version===1&&Array.isArray(saved.records)&&saved.records.length===3&&Number.isInteger(saved.active)&&saved.active>=0&&saved.active<3){active=saved.active;records=saved.records.map(r=>({...fresh(),...r,page:Math.max(1,Math.min(8,Number(r.page)||1))}));}}catch{}
const current=()=>records[active];
const data=()=>CASES[active];
let storageWarned=false;
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify({version:1,active,records}));}catch{if(!storageWarned){storageWarned=true;notify('이 브라우저에서는 진행 내용을 보관할 수 없습니다. 완료 후 보고서를 저장해 주세요.');}}}
function notify(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function button(text,action,kind='primary',disabled=false){return `<button class="${kind}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;}
function link(label,url){return `<a class="ghost source-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)} ↗</a>`;}
function input(label,id,value,placeholder='',limit=200){return `<label class="input-label" for="${id}">${label}</label><textarea id="${id}" maxlength="${limit}" placeholder="${escapeHtml(placeholder)}">${escapeHtml(value)}</textarea>`;}
function footer(next,disabled=false){return `<div class="actions">${button('이전 단계','back','ghost')}${button(next,'next','primary',disabled)}</div>`;}
function render(){clearInterval(timer);timer=null;const s=current(),d=data();$('app').innerHTML=`<section class="screen active" data-page="${s.page}"><div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">RO</span><span>ROAD ON 사회 변화 탐정단</span></div><div class="top-tools"><span class="case-chip">저출산 사건 0${active+1}</span>${button('수업 설정','teacher','ghost')}</div></header><div class="progress" aria-label="${s.page}/8 단계"><span style="width:${s.page/8*100}%"></span></div><div id="pageContent">${[intro,cluePage,articlePage,statsPage,fieldPage,comparePage,solvePage,reportPage][s.page-1]()}</div></div></section>`;$('pageLabel').textContent=`${s.page}페이지 ${pageNames[s.page-1]} · 사건 ${active+1}`;persist();}
function go(page){current().page=page;if(page===8)current().done=true;render();window.scrollTo({top:0,behavior:'instant'});}
function intro(){const s=current(),d=data();return `<div class="card intro-card"><div class="mission"><span class="kicker">오늘의 사건 · 먼저 질문해 보세요</span><h1>${escapeHtml(d.title)}</h1><p class="lead">${escapeHtml(d.question)}</p><div class="intro-writing">${input('나의 첫 예상','initial',s.initial,'여러 가지 예상이 가능해요. 왜 그렇게 생각했는지도 적어 보세요.')}${input('기사에서 알아보고 싶은 질문','initialQuestion',s.initialQuestion,'왜 그랬을까? 어떻게 달라졌을까? 궁금한 것을 적어 보세요.')}</div><div class="intro-actions"><p class="intro-cue">혼자 생각하기 → 짝과 이야기하기 → 단서로 다시 생각하기</p>${button('단서 봉투 열기','start','primary',!s.initial.trim()||!s.initialQuestion.trim())}</div></div></div>`;}
function cluePage(){const s=current(),d=data(),i=s.clue,c=d.clues[i],opened=s.opened[i],last=i===d.clues.length-1;return `<div class="card"><nav class="clue-index" aria-label="단서 목록">${d.clues.map((c,j)=>`<button class="clue-index-tab ${i===j?'current':''} ${s.completed[j]?'completed':''}" data-review="${j}" ${!s.completed[j]&&i!==j?'disabled':''}>${j+1}번째 단서${s.completed[j]?' · '+escapeHtml(c.value):i!==j?' 🔒':''}</button>`).join('')}</nav><div class="clue-instruction">${escapeHtml(d.title)}</div><div class="clue-layout"><div class="clue-stage">${opened?`<div class="clue-reveal"><div class="clue-paper-scene"><div class="clue-paper"><div class="clue-no">${i+1}번째 단서</div><div class="clue-value" data-length="${c.value.length>=5?'long':'medium'}">${escapeHtml(c.value)}</div><div class="clue-hint">${escapeHtml(c.hint)}</div></div><div class="open-envelope"><span class="open-envelope-label">ROAD ON · CLUE</span></div></div></div>`:`<button class="envelope" data-action="openEnvelope" aria-label="${i+1}번째 단서 봉투 열기"><span class="envelope-flap"></span><span class="envelope-seal">?</span><span class="envelope-caption">봉투를 눌러 단서 열기</span></button>`}</div><div class="clue-side"><aside class="activity-panel"><div class="activity-icon">🔎</div><h3 id="activityTitle">${opened?'정답보다 궁금한 점을 찾아보세요':'먼저 봉투를 열어보세요'}</h3><p id="activityText">${opened?'생각할 시간은 충분해요. 친구와 서로 다른 예상도 나누어 보세요.':'새 단서를 보고 첫 예상을 다시 생각해 보세요.'}</p></aside><aside class="thinking-box">${opened?`${input('이 단서를 보고 든 예상','clueNote',s.notes[i]||'','나는 …일 것 같아요. 그 까닭은 …입니다.')}${input('더 궁금해진 질문','clueQuestion',s.questions[i]||'','기사에서 무엇을 확인하고 싶나요?')}<div class="optional-help">${button('생각이 막힐 때 도움받기','help','help-button')}<div ${s.help[i]?'':'hidden'} id="helpCards"><p class="micro">이 낱말들은 정답이 아니에요. 다른 생각도 좋아요.</p><div class="word-choice-grid">${c.options.map(w=>`<button class="word-choice ${s.choices[i]===w?'selected':''}" data-word="${escapeHtml(w)}" aria-pressed="${s.choices[i]===w}">${escapeHtml(w)}</button>`).join('')}</div><p id="combination" class="micro">${s.choices[i]?escapeHtml(c.value+' + '+s.choices[i]+' — 어떤 관계일까요?'):''}</p></div></div><div class="reason-actions">${button(s.paired[i]?'친구와 이야기했어요 ✓':'친구와 이야기하기','pair','primary',!s.notes[i]?.trim()||!s.questions[i]?.trim())}${button(last?'기사문 수사 시작':'다음 단서 열기','advanceClue','secondary',!s.paired[i])}</div>`:'<p class="lead">단서는 하나씩 공개됩니다.</p><p>아직 보지 않은 단서를 먼저 맞힐 필요는 없어요.</p>'}</aside></div></div><div class="actions">${button('처음 질문 다시 보기','back','ghost')}</div></div>`;}
function articlePage(){const s=current(),d=data();const body=d.paragraphs.map(p=>'<p>'+escapeHtml(p).replace(/\[\[(.*?)\]\]/g,(_,word)=>`<button class="evidence-word ${s.evidence.includes(word)?'marked':''}" data-evidence="${word}" aria-pressed="${s.evidence.includes(word)}">${word}</button>` )+'</p>').join('');return `<div class="card"><div class="investigation-head"><h2>기사문 수사</h2><p class="lead">나의 질문에 답할 증거를 한 가지 이상 찾아 표시하세요.</p></div><details class="question-recap"><summary>내가 궁금했던 질문 다시 보기</summary><p>${escapeHtml(s.initialQuestion)}</p>${s.questions.map(q=>`<p>${escapeHtml(q)}</p>`).join('')}</details><div class="article-layout"><article class="article"><div class="newspaper-name"><span>ROAD ON 어린이 사회 신문</span><span>학교와 생활</span></div><h3>${escapeHtml(d.articleTitle)}</h3><div class="article-meta">${escapeHtml(d.meta)}</div><div class="article-body">${body}</div><p class="micro">제공된 수업 자료를 어린이용으로 재구성했습니다.<br>출처: <a href="${escapeHtml(d.source)}" target="_blank" rel="noopener noreferrer">${escapeHtml(d.sourceTitle)} ↗</a></p></article><aside class="word-help"><h3>기사 속 어려운 낱말</h3>${d.glossary.map(([w,m])=>`<details class="glossary-entry"><summary>${escapeHtml(w)}</summary><p>${escapeHtml(m)}</p></details>`).join('')}<p class="reading-note">${escapeHtml(d.caution)}</p></aside></div><div class="evidence-tray"><span id="evidenceCount">수집한 증거 ${s.evidence.length}개</span>${button('자료 수사로','next','primary',!s.evidence.length)}</div>${button('단서 다시 보기','back','ghost')}</div>`;}
function statsPage(){const s=current(),d=data();return `<div class="card"><h2>자료 수사</h2><p class="lead">누구의 수일까요? 무엇을 센 숫자일까요?</p><div class="stat-grid">${d.stats.map(([n,t])=>`<div class="data-card"><div class="stat-number">${escapeHtml(n)}</div><p>${escapeHtml(t)}</p></div>`).join('')}</div>${active===1?'<div class="trend"><strong>신입생 10명 미만 학교의 변화</strong><p>2023년 16곳 → 2024년 26곳 → 2025년 29곳</p></div>':''}<p class="reading-note">${escapeHtml(d.caution)}</p><h3>${escapeHtml(d.quiz)}</h3><div class="choice-grid">${d.answers.map((a,i)=>`<button class="choice ${s.answer===i?'selected':''}" data-answer="${i}" aria-pressed="${s.answer===i}">${escapeHtml(a)}</button>`).join('')}</div><p id="quizFeedback" role="status">${s.answer===null?'':s.answer===0?'숫자가 가리키는 대상을 잘 확인했어요.':'그 숫자는 누구를 센 것일까요? 자료를 다시 살펴보세요.'}</p>${footer('현장 확인하기',s.answer!==0)}</div>`;}
function fieldPage(){const s=current(),d=data();const regions=active===1?['강서구','기장군','영도구','금정구']:[d.place];return `<div class="card"><h2>현장 확인</h2><p class="lead">${escapeHtml(d.fieldQuestion)}</p><div class="field-grid"><div class="location-card"><span class="kicker">사건이 일어난 곳</span><p>${escapeHtml(d.region)}</p><h3>${escapeHtml(d.place)}</h3><p>${escapeHtml(d.address)}</p><div class="resource-links">${regions.map(r=>link(r+' 지도','https://map.naver.com/p/search/'+encodeURIComponent(active===1?'부산 '+r:r))).join('')}</div><div class="resource-links">${d.links.map(([l,u])=>link(l,u)).join('')}</div><p class="micro">지도와 자료는 새 창에서 열립니다. 확인한 뒤 이 화면으로 돌아오세요.</p></div><div class="watch-list"><h3>자료를 보고 확인했나요?</h3>${d.checks.map((t,i)=>`<label class="watch-item"><input type="checkbox" data-check="${i}" ${s.checks.includes(i)?'checked':''}> ${escapeHtml(t)}</label>`).join('')}${input('현장에서 찾은 내용','field',s.field,d.fieldPlaceholder,300)}</div></div>${footer('비교 탐구하기',!s.checks.length||!s.field.trim())}</div>`;}
function comparePage(){const s=current(),d=data();return `<div class="card"><h2>비교 탐구</h2><p class="lead">${escapeHtml(d.comparePrompt)}</p><div class="compare-grid">${d.compareLabels.map((label,i)=>`<div class="compare-column ${i?'hard':'good'}"><h3>${escapeHtml(label)}</h3>${d.compareOptions[i].map(t=>`<button class="compare-card ${s.compare[i]===t?'selected':''}" data-compare="${i}" data-value="${escapeHtml(t)}" aria-pressed="${s.compare[i]===t}">${escapeHtml(t)}</button>`).join('')}${input('나의 말로 적어도 좋아요',`compare${i}`,s.compare[i],'선택하거나 직접 적어 보세요.',160)}</div>`).join('')}</div>${footer('사건 해결하기',!s.compare.every(t=>t.trim()))}</div>`;}
function solvePage(){const s=current(),d=data();return `<div class="card"><h2>사건 해결</h2><p class="lead">처음의 질문에 답해 보세요. 카드로 시작하고 나의 말로 고쳐도 좋아요.</p><div class="sentence" id="sentencePreview">${escapeHtml(s.solution.filter(Boolean).join(' ')||'어떤 상황에서 → 무엇이 달라졌고 → 어떤 생활로 이어졌나요?')}</div>${['어떤 상황에서','어떤 변화가 생겼나요','생활은 어떻게 달라졌나요'].map((label,i)=>`<div class="solve-row"><h3>${i+1}. ${label}</h3><button class="word-card" data-solution="${i}">${escapeHtml(d.solve[i])}</button><label class="sr-only" for="solution${i}">${label}</label><input class="solution-input" id="solution${i}" maxlength="180" value="${escapeHtml(s.solution[i])}" placeholder="카드를 누르거나 직접 써 보세요."></div>`).join('')}<p class="micro">어린이 수의 변화는 저출산과 연결해 생각할 수 있어요. 지역의 인구 이동도 함께 살펴볼 필요가 있습니다.</p>${footer('탐정 보고서 만들기',!s.solution.every(t=>t.trim()))}</div>`;}
function reportPage(){const s=current(),d=data();return `<div class="report"><span class="kicker">증거로 생각을 바꾼 기록</span><h2>탐정 보고서</h2><h3>${escapeHtml(d.articleTitle)}</h3>${reportSections().map(([h,t])=>`<div class="report-section"><h3>${h}</h3><p>${escapeHtml(t)}</p></div>`).join('')}${input('나의 한 줄 생각','thought',s.thought,'처음과 달라진 생각이나 아직 남은 질문을 적어 보세요.',300)}<p class="micro">자료 출처: ${escapeHtml(d.meta)}</p></div><div class="actions">${button('이전 단계','back','ghost')}${button('PNG 이미지로 저장','save')}${button('세 사건 연결하기','connect','secondary',!records.every(r=>r.done))}${button('수업 설정','teacher','ghost')}</div><p class="micro">세 사건을 모두 탐구하면 연결 질문이 열립니다. 보고서는 이름 없이 이 브라우저에 보관됩니다.</p>`;}
function reportSections(){const s=current(),d=data();return [['처음에는 이렇게 예상했어요',s.initial],['내가 던진 질문',[s.initialQuestion,...s.questions].filter(Boolean).join(' / ')],['단서를 보고 다시 생각했어요',s.notes.map((n,i)=>`${d.clues[i].value}: ${n}`).join(' / ')],['기사에서 찾은 증거',s.evidence.join(' · ')],['현장에서 확인했어요',s.field],['비교해서 발견한 점',d.compareLabels.map((l,i)=>`${l}: ${s.compare[i]}`).join(' / ')],['이제는 이렇게 설명할 수 있어요',s.solution.join(' ')]];}
function modal(title,body){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;$('dialog').showModal();$('dialog').querySelector('input,button,textarea')?.focus();}
function codeThen(action){codeAction=action;modal('수업 진행 코드',`<p>선생님이 알려주는 네 자리 코드를 입력하세요.</p><input id="teacherCode" inputmode="numeric" maxlength="4" autocomplete="off" aria-label="수업 진행 코드"><p id="codeError" role="alert"></p><div class="actions">${button('돌아가기','close','ghost')}${button('확인','confirmCode')}</div>`);}
function teacherPanel(){modal('오늘의 사건 선택',`<p>한 차시에는 사건 하나를 골라 탐구합니다. 다른 사건의 기록도 보관됩니다.</p><div class="choice-grid">${CASES.map((d,i)=>`<button class="choice" data-case="${i}">사건 ${i+1} · ${escapeHtml(d.title)}${records[i].done?' ✓':''}${i===active?' (현재)':''}</button>`).join('')}</div><div class="actions">${button('현재 사건 처음부터','reset','ghost')}${button('돌아가기','close','secondary')}</div><p class="micro">진행 코드는 보안용 비밀번호가 아니라 수업 진행을 위한 장치입니다.</p>`);}
function canNext(){const s=current();return s.page===3?s.evidence.length>0:s.page===4?s.answer===0:s.page===5?s.checks.length>0&&s.field.trim():s.page===6?s.compare.every(t=>t.trim()):s.page===7?s.solution.every(t=>t.trim()):false;}
function updateButtons(){const s=current();document.querySelectorAll('[data-action="start"]').forEach(b=>b.disabled=!s.initial.trim()||!s.initialQuestion.trim());document.querySelectorAll('[data-action="pair"]').forEach(b=>b.disabled=!s.notes[s.clue]?.trim()||!s.questions[s.clue]?.trim());document.querySelectorAll('[data-action="advanceClue"]').forEach(b=>b.disabled=!s.paired[s.clue]);document.querySelectorAll('[data-action="next"]').forEach(b=>b.disabled=!canNext());}
document.addEventListener('input',e=>{const s=current(),id=e.target.id,value=e.target.value;if(['initial','initialQuestion','field','thought'].includes(id))s[id]=value;else if(id==='clueNote'||id==='clueQuestion'){s[id==='clueNote'?'notes':'questions'][s.clue]=value;s.paired[s.clue]=false;const pair=document.querySelector('[data-action="pair"]');if(pair)pair.textContent='친구와 이야기하기';}else if(/^compare[01]$/.test(id)){s.compare[Number(id.slice(-1))]=value;document.querySelectorAll(`[data-compare="${id.slice(-1)}"]`).forEach(b=>{b.classList.toggle('selected',b.dataset.value===value);b.setAttribute('aria-pressed',String(b.dataset.value===value));});}else if(/^solution[012]$/.test(id)){s.solution[Number(id.slice(-1))]=value;$('sentencePreview').textContent=s.solution.filter(Boolean).join(' ');}else return;updateButtons();persist();});
document.addEventListener('change',e=>{if(e.target.hasAttribute('data-check')){const i=Number(e.target.dataset.check),s=current();s.checks=s.checks.filter(x=>x!==i);if(e.target.checked)s.checks.push(i);updateButtons();persist();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const s=current(),d=data(),a=b.dataset.action;
 if(b.hasAttribute('data-evidence')){const w=b.dataset.evidence;s.evidence=s.evidence.includes(w)?s.evidence.filter(x=>x!==w):[...s.evidence,w];b.classList.toggle('marked',s.evidence.includes(w));b.setAttribute('aria-pressed',String(s.evidence.includes(w)));$('evidenceCount').textContent=`수집한 증거 ${s.evidence.length}개`;updateButtons();persist();return;}
 if(b.hasAttribute('data-answer')){s.answer=Number(b.dataset.answer);render();return;}
 if(b.hasAttribute('data-compare')){const i=Number(b.dataset.compare);s.compare[i]=b.dataset.value;render();return;}
 if(b.hasAttribute('data-solution')){const i=Number(b.dataset.solution);s.solution[i]=d.solve[i];render();return;}
 if(b.hasAttribute('data-word')){s.choices[s.clue]=b.dataset.word;document.querySelectorAll('[data-word]').forEach(w=>{w.classList.toggle('selected',w===b);w.setAttribute('aria-pressed',String(w===b));});$('combination').textContent=d.clues[s.clue].value+' + '+b.dataset.word+' — 어떤 관계일까요?';persist();return;}
 if(b.hasAttribute('data-review')){const i=Number(b.dataset.review);if(i===s.clue||!s.completed[i])return;modal(`${i+1}번째 단서 다시 보기`,`<h2>${escapeHtml(d.clues[i].value)}</h2><p>${escapeHtml(d.clues[i].hint)}</p><h3>나의 예상</h3><p>${escapeHtml(s.notes[i])}</p><h3>나의 질문</h3><p>${escapeHtml(s.questions[i])}</p>${button('현재 단서로 돌아가기','close')}`);return;}
 if(b.hasAttribute('data-case')){active=Number(b.dataset.case);$('dialog').close();render();window.scrollTo(0,0);return;}
 if(a==='start'&&s.initial.trim()&&s.initialQuestion.trim())go(2);
 if(a==='back')go(Math.max(1,s.page-1));
 if(a==='next'&&canNext())go(s.page+1);
 if(a==='openEnvelope'){s.opened[s.clue]=true;render();let seconds=8;$('activityTitle').textContent='단서를 자세히 살펴보세요 · 8초';$('activityText').textContent='보이는 낱말과 숫자에서 어떤 질문이 떠오르나요?';timer=setInterval(()=>{seconds--;$('activityTitle').textContent=seconds>0?`단서를 자세히 살펴보세요 · ${seconds}초`:'혼자 충분히 생각해 보세요';if(seconds<=0){clearInterval(timer);timer=null;$('activityText').textContent='시간 제한은 없어요. 예상과 궁금한 질문을 적고 친구와 나누세요.';}},1000);}
 if(a==='help'){s.help[s.clue]=true;$('helpCards').hidden=false;persist();}
 if(a==='pair'&&s.notes[s.clue]?.trim()&&s.questions[s.clue]?.trim()){s.paired[s.clue]=true;b.textContent='친구와 이야기했어요 ✓';updateButtons();persist();modal('친구와 서로 물어보세요',`<p>나의 예상과 질문을 설명해 보세요.</p><p><strong>“왜 그렇게 생각했어?”<br>“기사에서 무엇을 확인하면 좋을까?”</strong></p>${button('이야기를 이어가며 돌아가기','close')}`);}
 if(a==='advanceClue'&&s.paired[s.clue])codeThen(()=>{s.completed[s.clue]=true;if(s.clue<d.clues.length-1){s.clue++;render();}else go(3);});
 if(a==='teacher')codeThen(teacherPanel);
 if(a==='confirmCode'){if($('teacherCode').value!=='2026'){$('codeError').textContent='수업 진행 코드를 다시 확인해 주세요.';$('teacherCode').focus();return;}const fn=codeAction;codeAction=null;$('dialog').close();fn?.();}
 if(a==='close')$('dialog').close();
 if(a==='reset')modal('현재 사건의 기록을 지울까요?',`<p>현재 사건의 예상, 질문, 탐구 기록이 지워집니다. 다른 사건의 기록은 남습니다.</p><div class="actions">${button('취소','close','ghost')}${button('현재 사건 다시 시작','resetConfirm')}</div>`);
 if(a==='resetConfirm'){records[active]=fresh();$('dialog').close();render();}
 if(a==='connect'&&records.every(r=>r.done))modal('세 사건을 연결해 보세요',`<h3>학생 수가 줄어든 지역에서는 학교의 모습이 어떻게 달라졌을까요?</h3>${CASES.map(c=>`<p class="reading-note">${escapeHtml(c.summary)}</p>`).join('')}<p><strong>부안과 창녕은 어떤 다른 방법을 선택했나요?</strong></p><p>우리 지역이라면 어떤 점을 살펴보고 방법을 선택하면 좋을까요?</p>${button('보고서로 돌아가기','close')}`);
 if(a==='save')saveReport();
});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='teacherCode'){e.preventDefault();document.querySelector('[data-action="confirmCode"]')?.click();}});
function saveReport(){const s=current(),d=data(),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1200;canvas.height=2000;const blocks=[['사건',d.articleTitle],...reportSections(),['나의 한 줄 생각',s.thought||'아직 적지 않았어요.'],['자료 출처',d.meta]];const lines=(text,width)=>{let out=[],line='';for(const word of String(text).split(/\s+/)){const candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width>width&&line){out.push(line);line=word;}else line=candidate;}if(line)out.push(line);return out;};ctx.font='26px sans-serif';const laid=blocks.map(([title,text])=>({title,lines:lines(text,1040)}));canvas.height=230+laid.reduce((n,b)=>n+88+b.lines.length*40,0);ctx.fillStyle='#fffaf0';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#163b38';ctx.fillRect(0,0,1200,160);ctx.fillStyle='#f6c453';ctx.font='bold 28px sans-serif';ctx.fillText('ROAD ON 사회 변화 탐정단',80,60);ctx.fillStyle='#fff';ctx.font='bold 44px sans-serif';ctx.fillText(`사건 ${active+1} · 탐정 보고서`,80,122);let y=225;laid.forEach(block=>{ctx.fillStyle='#163b38';ctx.font='bold 30px sans-serif';ctx.fillText(block.title,80,y);y+=45;ctx.fillStyle='#293733';ctx.font='26px sans-serif';block.lines.forEach(line=>{ctx.fillText(line,80,y);y+=40;});y+=43;});const a=document.createElement('a');a.download=`ROAD-ON_저출산_사건${active+1}_탐정보고서.png`;a.href=canvas.toDataURL('image/png');a.click();notify('탐정 보고서 이미지를 저장했습니다.');}
render();
